# Generated by Django 5.0.6 on 2024-05-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_book.books'),
        ),
    ]
