# Generated by Django 5.0.6 on 2024-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_alter_profile_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
