# Generated by Django 5.0.6 on 2024-06-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0003_books_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_books',
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='app_book.books')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf', to='app_book.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(null=True, to='app_book.books'),
        ),
    ]
