# Generated by Django 5.0.6 on 2024-06-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0006_bookreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookshelf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookshelf', to='app_book.bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.books'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_profile', to='app_book.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='app_book.books'),
        ),
    ]
