# Generated by Django 5.0.6 on 2024-06-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0007_profile_bookshelf_alter_bookreview_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookshelf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookshelf', to='app_book.bookshelf'),
        ),
    ]
