# Generated by Django 5.0.6 on 2024-06-02 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0008_alter_profile_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_profile', to='app_book.profile'),
        ),
    ]
