# Generated by Django 5.0.6 on 2024-06-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0010_alter_bookshelf_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookshelf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookshelf', to='app_book.bookshelf'),
        ),
    ]
