# Generated by Django 5.0.6 on 2024-06-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0012_auto_20240602_1601'),
        ('app_book', 'migration'),
    ]

    operations = [
    ]
